plaintext = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ciphertext = "EFGHABCDQRSTUVWXMNOPYZIJKL"
encrypted = "ETEVHTWGSAHGWYVPNKQOEGWYVPNKPDEPHWAOVWPFWNHANEVWXAVOAEAJEUXTAOWBTEVHTWGSAHGWYVPNQAOQVGTYHAVAXETOANFQEOIQPLANTEVHFYNSQVEBEOWSKNCKLOPEVTYJAUFWYNCOTWZESQEPERQSQOPEVYCEVHEGDEHEVHEYOPNQEEHWYFTKTEVHTWGSAHGWYVPNKQOWVAPDEPWVTKFWNHANOTEVHTWGSAHGWYVPNQAOPDANAENAWVTKPIWHWYFTKTEVHTWGSAHGWYVPNQAOQVPDAIWNTHWVAWBPDAUQOYLFASQOPEVIDEPQOPDAWPDANWVA"

msg = ""

for c in encrypted:
    if c >= 'A' and c <= 'Z':
        c = plaintext[ciphertext.index(c)]
    msg = msg + c

print(msg)
